spring:
  datasource:
    driver-class-name: Altibase.jdbc.driver.AltibaseDriver
    url: jdbc:Altibase://192.168.0.1:20300/precheck
    username: precheck
    password: precheck

precheck:
  collect:
    schedule-file-path: /home/precheck/cfg/PreCheck_CollectLogs_Schedule.conf
  sftp:
    port: 22
    username: prod_user
    password: prod_pass
